import type { HubChannel } from '../types';

const CHANNEL_SLUGS: Record<string, string> = {
  // Das Erste
  'daserste':          'das-erste',
  'das-erste':         'das-erste',
  'daserste.de':       'das-erste',
  'das-erste.de':      'das-erste',

  // ZDF
  'zdf':               'zdf',
  'zdf.de':            'zdf',
  'zdf_neo':           'zdf-neo',
  'zdfneo':            'zdf-neo',
  'zdf-neo':           'zdf-neo',
  'zdf_neo.de':        'zdf-neo',
  'zdfneo.de':         'zdf-neo',
  'zdf-neo.de':        'zdf-neo',
  'zdfinfo':           'zdfinfo',
  'zdf-info':          'zdfinfo',
  'zdfinfo.de':        'zdfinfo',

  // RTL Group
  'rtl':               'rtl',
  'rtl.de':            'rtl',
  'rtlzwei':           'rtl2',
  'rtl2':              'rtl2',
  'rtl-2':             'rtl2',
  'rtlzwei.de':        'rtl2',
  'superrtl':          'super-rtl',
  'super-rtl':         'super-rtl',
  'superrtl.de':       'super-rtl',
  'nitro':             'nitro',
  'nitro.de':          'nitro',
  'vox':               'vox',
  'vox.de':            'vox',
  'voxup':             'voxup',
  'vox-up':            'voxup',
  'voxup.de':          'voxup',
  'n-tv':              'n-tv',
  'ntv':               'n-tv',
  'n-tv.de':           'n-tv',

  // ProSiebenSat.1
  'prosieben':         'prosieben',
  'pro7':              'prosieben',
  'prosieben.de':      'prosieben',
  'prosiebenmaxx':     'prosieben-maxx',
  'prosieben-maxx':    'prosieben-maxx',
  'prosiebenmaxx.de':  'prosieben-maxx',
  'prosiebenfun':      'prosieben-fun',
  'prosieben-fun':     'prosieben-fun',
  'sat1':              'sat1',
  'sat.1':             'sat1',
  'sat-1':             'sat1',
  'sat1.de':           'sat1',
  'sat1gold':          'sat1-gold',
  'sat1-gold':         'sat1-gold',
  'sat1gold.de':       'sat1-gold',
  'sat1emotions':      'sat1-emotions',
  'sat1-emotions':     'sat1-emotions',
  'kabeleins':         'kabel-eins',
  'kabel-eins':        'kabel-eins',
  'kabel1':            'kabel-eins',
  'kabeleins.de':      'kabel-eins',
  'kabeleinsdoku':     'kabel-eins-doku',
  'kabel-eins-doku':   'kabel-eins-doku',
  'kabeleinsclassics': 'kabel-eins-classics',
  'sixx':              'sixx',
  'sixx.de':           'sixx',

  // Öffentliche & Sparten
  '3sat':              '3sat',
  '3sat.de':           '3sat',
  'arte':              'arte',
  'arte.de':           'arte',
  'phoenix':           'phoenix',
  'phoenix.de':        'phoenix',
  'one':               'one',
  'one.de':            'one',
  'tele5':             'tele5',
  'tele-5':            'tele5',
  'tele5.de':          'tele5',
  'welt':              'welt',
  'welt.de':           'welt',
  'kika':              'kika',
  'kika.de':           'kika',
  'tagesschau24':      'tagesschau24',
  'tagesschau24.de':   'tagesschau24',
  'ard-alpha':         'ard-alpha',
  'ardalpha':          'ard-alpha',
  'ard-alpha.de':      'ard-alpha',
  'sport1':            'sport1',
  'sport-1':           'sport1',
  'sport1.de':         'sport1',
  'dmax':              'dmax',
  'dmax.de':           'dmax',
  'hse24':             'hse24',
  'hse-24':            'hse24',
  'hse24.de':          'hse24',
  'hse':               'hse',
  'hse.de':            'hse',
  'qvc':               'qvc',
  'qvc.de':            'qvc',
  'qvczwei':           'qvc-zwei',
  'qvc-zwei':          'qvc-zwei',
  'qvczwei.de':        'qvc-zwei',
  'ndr':               'ndr',
  'ndr.de':            'ndr',
  'wdr':               'wdr',
  'wdr.de':            'wdr',
  'br':                'br',
  'br.de':             'br',
  'swr':               'swr',
  'swr.de':            'swr',
  'hr':                'hr',
  'hr.de':             'hr',
  'mdr':               'mdr',
  'mdr.de':            'mdr',
  'rbb':               'rbb',
  'rbb.de':            'rbb',
};

export const normCid = (cid: string): string => {
  if (!cid || typeof cid !== 'string') return '';
  const cleaned = cid.toLowerCase().trim().replace(/^de-/, '').replace(/\.de$/, '');
  return CHANNEL_SLUGS[cleaned] ?? CHANNEL_SLUGS[cid.toLowerCase().trim()] ?? cleaned.replace(/\s+/g, '-');
};

export const getChannelSlug = normCid;

export const getHubChannelUrl = (channelId: string): string =>
  `/${normCid(channelId)}/`;

/** Canali TV principali tedeschi esposti come hub (ordine audience reach AGF 2025) */
export const HUB_CHANNELS: HubChannel[] = [
  { id: 'rtl',          name: 'RTL'         },
  { id: 'zdf',          name: 'ZDF'         },
  { id: 'das-erste',    name: 'Das Erste'   },
  { id: 'sat1',         name: 'SAT.1'       },
  { id: 'prosieben',    name: 'ProSieben'   },
  { id: 'vox',          name: 'VOX'         },
  { id: 'rtl2',         name: 'RTL2'        },
  { id: 'kabel-eins',   name: 'Kabel Eins'  },
  { id: 'sixx',         name: 'sixx'        },
  { id: 'super-rtl',    name: 'Super RTL'   },
  { id: 'nitro',        name: 'NITRO'       },
  { id: 'tele5',        name: 'Tele 5'      },
  { id: 'zdf-neo',      name: 'ZDFneo'      },
  { id: 'zdfinfo',      name: 'ZDFinfo'     },
  { id: '3sat',         name: '3sat'        },
  { id: 'arte',         name: 'ARTE'        },
  { id: 'phoenix',      name: 'phoenix'     },
  { id: 'one',          name: 'One'         },
  { id: 'sport1',       name: 'SPORT1'      },
  { id: 'dmax',         name: 'DMAX'        },
];
